# Generated by Django 4.2.1 on 2023-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingmodel',
            name='category',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('ZL', 'ZL'), ('Wspolne', 'Wspolne')], max_length=50),
        ),
    ]
