# Generated by Django 4.2.1 on 2023-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0002_alter_savingmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='savingmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingmodel',
            name='name',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('PLN', 'Polish Zloty')], max_length=3, unique=True),
        ),
    ]
