# Generated by Django 4.2.1 on 2023-06-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0004_rename_name_savingmodel_currency_savingmodelaccess'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingmodelaccess',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='savingmodel',
            name='users',
            field=models.ManyToManyField(through='Savings.SavingModelAccess', to='accounts.userprofile'),
        ),
    ]
